- icon: stethoscope
  title: IT活用健康診断
  desc: 現代はITをまったく活用しないのはビジネスの機会損失ですが、何も考えずにITを使うのはムダです。ガリガリでもメタボでもない健康的なIT活用のため、最小限のコストで最大限の価値を得るための本当に必要なIT活用について健康診断を行います。
- icon: cogs
  title: ITビジネスコンサルティング
  desc: 御社のITサービスが最小投資、最大価値を生み出すようにコンサルティングします。ムダなIT投資はさせません。
- icon: pagelines
  title: 組織の共有ビジョンづくり
  desc: 組織が機能するためには、人々が心を突き動かされる共有ビジョンが不可欠です。パタン・ランゲージを用いてあなたの組織のビジョンづくり、その実施を強力にサポートします。
- icon: thumbs-o-up
  title: 社外CTO(Chief Technical Officer)/CAO(Chief Agile Officer)
  desc: 社内に信頼できるCTOがいない、企業をアジャイルに変革したいができる人材がいない、そんな時には社外CTO、CAOとして継続的に御社のビジネス革新を助けます。
